---
apiVersion: v1
kind: Service
metadata:
  name: &app octoprint-cam
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: "10.26.20.91"
  ports:
    - name: http
      port: &port 8081
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app octoprint-cam
  namespace: networking
  annotations:
    hajimari.io/icon: mdi:printer-3d
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: nginx
  rules:
    - host: &host "octoprint-cam.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 8081
  tls:
    - hosts:
        - *host
