---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-redis
  namespace: security
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: 17.11.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      remediateLastFailure: true
    architecture: standalone
    auth:
      enabled: true
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 1
      persistence:
        enabled: false
