---
version: "3"

vars:
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes"
  INFRASTRUCTURE_DIR: "{{.ROOT_DIR}}/infrastructure"

dotenv: [".config.env"]

env:
  KUBECONFIG: ./kubeconfig
  SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt

includes:
  es: .taskfiles/ExternalSecrets/Tasks.yml
  fx: .taskfiles/Flux/Tasks.yml
  ku: .taskfiles/Kubernetes/Tasks.yml
  vs: .taskfiles/VolSync/Tasks.yml
  olda: .taskfiles/OLD/AnsibleTasks.yml
  oldc: .taskfiles/OLD/ClusterTasks.yml
  oldp: .taskfiles/OLD/PrecommitTasks.yml
  oldt: .taskfiles/OLD/TerraformTasks.yml

tasks:

  default:
    silent: true
    cmds: ["task -l"]
