---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: protonmail-bridge
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controller:
      strategy: Recreate
    image:
      repository: ghcr.io/seandonohoo/proton-mail-bridge
      tag: 3.0.20@sha256:d778171757677d19bea9881ddb0e226efc40f4128ae00372f031eee6d08ebfc3
    env:
      TZ: "America/Chicago"
    service:
      main:
        enabled: false
      imap:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_PROTON_BRIDGE}"
        annotations:
          coredns.io/hostname: "imap.${SECRET_DOMAIN}"
          metallb.universe.tf/allow-shared-ip: mail-svc
        externalTrafficPolicy: Local
        ports:
          imap-tcp:
            enabled: true
            port: 143
      smtp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_PROTON_BRIDGE}"
        annotations:
          coredns.io/hostname: "smtp.${SECRET_DOMAIN}"
          metallb.universe.tf/allow-shared-ip: mail-svc
        externalTrafficPolicy: Local
        ports:
          smtp-tcp:
            enabled: true
            port: 25
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: protonmail-bridge-config-v1
        mountPath: /root
