---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: download
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, RADARR__API_KEY
        key: radarr
