---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 15m

  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2023.5.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 15m

  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.6.0

    geoip:
      enabled: false

    envFrom:
      - secretRef:
          name: authentik-secret

    authentik:
      log_level: debug
      secret_key: "${AUTHENTIK_SECRET_KEY}"
      email:
        host: "${SMTP_HOST}"
        port: "${SMTP_PORT}"
        username: "${SMTP_USER}"
        password: "${SMTP_PASS}"
        use_tls: true
        from: "${SMTP_FROM}"
      error_reporting:
        enabled: false
        send_pii: false
      postgresql:
        host: "${POSTGRES_HOST}"
        port: 5432
        name: ""
        user: ""
        password: ""
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

    envValueFrom:
      AUTHENTIK_POSTGRESQL__HOST:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRES_HOST
      AUTHENTIK_POSTGRESQL__NAME:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRES_DB
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRES_USER
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRES_PASS

    postgresql:
      enabled: false
    redis:
      enabled: true

    prometheus:
      rules:
        create: false
      serviceMonitor:
        create: true

    podAnnotations:
      secret.reloader.stakater.com/reload: authentik-secret

  valuesFrom:
    # GEOIP
    - kind: Secret
      name: authentik-secret
      valuesKey: GEOIP_ACCOUNT_ID
      targetPath: geoip.accountId
      optional: false
    - kind: Secret
      name: authentik-secret
      valuesKey: GEOLITE_LICENSE_KEY
      targetPath: geoip.licenseKey
      optional: false
