---
# (string) Timezone for the servers
# timezone: "America/New_York"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

fedora:
  packages:
    - dnf-plugin-system-upgrade
    - dnf-utils
    - hdparm
    - htop
    - ipvsadm
    - lm_sensors
    - nano
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-libselinux
    - python3-pyyaml

ubuntu:
  packages:
    - apt-transport-https
    - arptables
    - ca-certificates
    - curl
    - ebtables
    - fish
    - fzf
    - gdisk
    - hdparm
    - htop
    - iputils-ping
    - ipvsadm
    - lm-sensors
    - lvm2
    - nano
    - net-tools
    - nfs-common
    - ntpdate
    - nvme-cli
    - open-iscsi
    - psmisc
    - python3-kubernetes
    - python3-yaml
    - smartmontools
    - socat
    - software-properties-common
    - unzip
