---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.26.10.100"
  SVC_REDIS_ADDR: "10.26.35.110"
  SVC_QBITTORRENT_ADDR: "10.26.35.120"
  SVC_PROTON_BRIDGE: "10.26.35.114"
